# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{interpolate}
  s.version = "0.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Collins"]
  s.date = %q{2011-04-10}
  s.description = %q{Description

Library for generic Interpolation objects. Useful for such things as generating
linear motion between points (or arrays of points), multi-channel color
gradients, piecewise functions, or even just placing values within intervals.
}
  s.email = %q{adam@m104.us}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
    "LICENSE",
    "Manifest.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "examples/arrays.rb",
    "examples/buckets.rb",
    "examples/colors.rb",
    "examples/nested.rb",
    "interpolate.gemspec",
    "lib/interpolate.rb",
    "lib/interpolate/add/core.rb",
    "lib/interpolate/add/core/array.rb",
    "lib/interpolate/add/core/numeric.rb",
    "lib/interpolate/interpolation.rb",
    "test/test_all.rb"
  ]
  s.homepage = %q{http://github.com/m104/interpolate}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Create linear interpolations from key points and values}
  s.test_files = [
    "examples/arrays.rb",
    "examples/buckets.rb",
    "examples/colors.rb",
    "examples/nested.rb",
    "test/test_all.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

